DELETE  http://localhost:3001/api/persons/1

###
GET http://localhost:3001/api/persons/1

###
GET http://localhost:3001/api/persons/

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "dalice",
  "number": "021-342430-492"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "dalice"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "gupta",
  "number": "021-342430-492"
}